# Generated by Django 3.2.19 on 2024-01-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceSnapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('cpu', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('gpu', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('total_duration', models.FloatField()),
                ('load_duration', models.FloatField()),
                ('prompt_eval_count', models.IntegerField()),
                ('prompt_eval_duration', models.FloatField()),
                ('prompt_eval_rate', models.FloatField()),
                ('eval_count', models.IntegerField()),
                ('eval_duration', models.FloatField()),
                ('eval_rate', models.FloatField()),
            ],
        ),
    ]
