# Generated by Django 3.2.19 on 2024-01-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancesnapshot',
            name='llm_model',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='performancesnapshot',
            name='ram',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='performancesnapshot',
            name='vram',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
