# Generated by Django 3.2.19 on 2024-01-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_performance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancesnapshot',
            name='purchase_price',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='performancesnapshot',
            name='purchase_year',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
