# Generated by Django 3.2.19 on 2024-01-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_performance', '0002_auto_20240107_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancesnapshot',
            name='operating_system',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
