# Generated by Django 3.2.19 on 2024-01-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_performance', '0003_performancesnapshot_operating_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancesnapshot',
            name='llm_model',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True),
        ),
    ]
