# Generated by Django 3.2.19 on 2024-01-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_performance', '0004_alter_performancesnapshot_llm_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancesnapshot',
            name='cpu_cores',
            field=models.IntegerField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
