# Generated by Django 3.2.19 on 2024-01-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm_performance', '0005_performancesnapshot_cpu_cores'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('llm_model', models.CharField(blank=True, db_index=True, default=None, max_length=128, null=True)),
            ],
        ),
    ]
