# Generated by Django 3.2.19 on 2024-01-20 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm_performance', '0006_sampleinput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sampleinput',
            old_name='llm_model',
            new_name='name',
        ),
    ]
