# Generated by Django 3.2.19 on 2023-12-31 14:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('contact_email', models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('email_notifications_enabled', models.BooleanField(default=True, help_text='Enable email notifications', verbose_name='Email notifications')),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'base_manager_name': 'profiles',
                'default_manager_name': 'profiles',
            },
            managers=[
                ('profiles', django.db.models.manager.Manager()),
            ],
        ),
    ]
