# Generated by Django 3.2.19 on 2024-01-02 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(help_text='user e-mail address', max_length=255, unique=True, verbose_name='e-mail address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='contact_email',
            field=models.CharField(max_length=255, validators=[django.core.validators.EmailValidator()], verbose_name='e-mail'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='enable e-mail notifications', verbose_name='e-mail notifications'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='person_name',
            field=models.CharField(max_length=255, verbose_name='user name'),
        ),
    ]
