# Generated by Django 3.2.19 on 2024-01-12 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240102_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trusted',
            field=models.BooleanField(default=False),
        ),
    ]
