# Generated by Django 3.2.19 on 2024-01-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='IP address')),
                ('first_seen', models.DateTimeField(auto_now_add=True, db_index=True, help_text='First time seen')),
                ('counter', models.IntegerField(db_index=True, default=1, help_text='Requests counter')),
            ],
        ),
    ]
